### ISSUE TITLE
Decoding error when using leader()

### ISSUE THREAD

**Issue by nh2** [cablehead/python-consul#152]
In a script that does the following:

```python
#!/usr/bin/env python3

import argparse
import consul
import logging
import subprocess
import sys
import time

from requests.exceptions import ConnectionError


def waitForLeader(args):
  c = consul.Consul()

  got_leader = False
  while not got_leader:
    try:
      leader_output = c.status.leader()
      if leader_output != '':
        logging.debug("got leader: {0}".format(leader_output))
        got_leader = True
      else:
        logging.debug("got empty leader")
    except ConnectionError:
      logging.info("got connection error when trying to connect to consul")
    time.sleep(0.1)
```

I got this stacktrace:

```
Traceback (most recent call last):
  File "myscript", line 19, in waitForLeader
    leader_output = c.status.leader()
  File "/nix/store/ajb72yjnfbnjab09nqhh2rdrkbdshi6i-python3-3.6.1-env/lib/python3.6/site-packages/consul/base.py", line 1832, in leader
    lambda x: json.loads(x.body), '/v1/status/leader')
  File "/nix/store/ajb72yjnfbnjab09nqhh2rdrkbdshi6i-python3-3.6.1-env/lib/python3.6/site-packages/consul/std.py", line 34, in get
    self.session.get(uri, verify=self.verify)))
  File "/nix/store/ajb72yjnfbnjab09nqhh2rdrkbdshi6i-python3-3.6.1-env/lib/python3.6/site-packages/consul/base.py", line 1832, in <lambda>
    lambda x: json.loads(x.body), '/v1/status/leader')
  File "/nix/store/ajb72yjnfbnjab09nqhh2rdrkbdshi6i-python3-3.6.1-env/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/nix/store/ajb72yjnfbnjab09nqhh2rdrkbdshi6i-python3-3.6.1-env/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/ajb72yjnfbnjab09nqhh2rdrkbdshi6i-python3-3.6.1-env/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I'm using consul 0.7.5 here.

It seems that this is happening only when the consul being asked for the leader is a consul agent, not a when it's a consul server (then it returns `""` as expected).

Is it possible that the library doesn't check the HTTP error code in this case?

Because consul can return `No known Consul servers` or `rpc error: EOF`, which is not a parseable JSON value, but the HTTP error code will be set to 500 in such cases.

**Comment by nh2** [comment]
I was using an older version, 0.6.0.

Turns out this was fixed in version 0.7.0.

That version returns `consul.base.ConsulException: 500 No known Consul servers` as expected.
